# Generated by Django 6.0.3 on 2026-04-16 10:21

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = []

    operations = [
        migrations.CreateModel(
            name="Course",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("name", models.CharField(max_length=100, verbose_name="课程名称")),
                (
                    "code",
                    models.CharField(max_length=6, unique=True, verbose_name="课程码"),
                ),
                ("semester", models.CharField(max_length=50, verbose_name="学期")),
                (
                    "description",
                    models.TextField(blank=True, null=True, verbose_name="课程描述"),
                ),
                (
                    "create_time",
                    models.DateTimeField(auto_now_add=True, verbose_name="创建时间"),
                ),
            ],
            options={
                "verbose_name": "课程",
                "verbose_name_plural": "课程",
            },
        ),
        migrations.CreateModel(
            name="Question",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("title", models.CharField(max_length=500, verbose_name="题目内容")),
                (
                    "q_type",
                    models.IntegerField(
                        verbose_name="题型：1单选 2多选 3判断 4填空 5简答"
                    ),
                ),
                (
                    "level",
                    models.IntegerField(
                        default=1, verbose_name="难度：1简单 2中等 3困难"
                    ),
                ),
                ("course", models.CharField(max_length=50, verbose_name="科目")),
                (
                    "options",
                    models.TextField(
                        blank=True, null=True, verbose_name="选项（A.xx,B.xx）"
                    ),
                ),
                ("answer", models.CharField(max_length=200, verbose_name="正确答案")),
            ],
        ),
        migrations.CreateModel(
            name="User",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "username",
                    models.CharField(max_length=50, unique=True, verbose_name="用户名"),
                ),
                ("password", models.CharField(max_length=100, verbose_name="密码")),
                (
                    "role",
                    models.IntegerField(default=2, verbose_name="角色：1教师 2学生"),
                ),
                ("name", models.CharField(max_length=50, verbose_name="姓名")),
            ],
        ),
        migrations.CreateModel(
            name="Task",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("title", models.CharField(max_length=200, verbose_name="任务标题")),
                (
                    "description",
                    models.TextField(blank=True, null=True, verbose_name="任务描述"),
                ),
                (
                    "create_time",
                    models.DateTimeField(auto_now_add=True, verbose_name="创建时间"),
                ),
                (
                    "duration",
                    models.IntegerField(default=10, verbose_name="时长（分钟）"),
                ),
                (
                    "end_time",
                    models.DateTimeField(
                        blank=True, null=True, verbose_name="结束时间"
                    ),
                ),
                (
                    "status",
                    models.IntegerField(
                        default=1, verbose_name="状态：1进行中 2已结束"
                    ),
                ),
                (
                    "course",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="tasks",
                        to="user_app.course",
                        verbose_name="所属课程",
                    ),
                ),
                (
                    "questions",
                    models.ManyToManyField(
                        to="user_app.question", verbose_name="题目列表"
                    ),
                ),
                (
                    "create_by",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        to="user_app.user",
                        verbose_name="创建教师",
                    ),
                ),
            ],
            options={
                "verbose_name": "任务",
                "verbose_name_plural": "任务",
            },
        ),
        migrations.AddField(
            model_name="question",
            name="create_by",
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.CASCADE,
                to="user_app.user",
                verbose_name="创建教师",
            ),
        ),
        migrations.AddField(
            model_name="course",
            name="teacher",
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.CASCADE,
                related_name="teaching_courses",
                to="user_app.user",
                verbose_name="授课教师",
            ),
        ),
        migrations.CreateModel(
            name="AnswerRecord",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "student_answer",
                    models.CharField(max_length=200, verbose_name="学生答案"),
                ),
                (
                    "is_correct",
                    models.BooleanField(
                        blank=True,
                        default=None,
                        null=True,
                        verbose_name="是否正确（None表示待批改）",
                    ),
                ),
                (
                    "question",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        to="user_app.question",
                        verbose_name="答题题目",
                    ),
                ),
                (
                    "task",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        to="user_app.task",
                        verbose_name="所属任务",
                    ),
                ),
                (
                    "student",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        to="user_app.user",
                        verbose_name="答题学生",
                    ),
                ),
            ],
            options={
                "verbose_name": "答题记录",
                "verbose_name_plural": "答题记录",
            },
        ),
        migrations.CreateModel(
            name="CourseStudent",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "join_time",
                    models.DateTimeField(auto_now_add=True, verbose_name="加入时间"),
                ),
                (
                    "course",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="student_records",
                        to="user_app.course",
                        verbose_name="课程",
                    ),
                ),
                (
                    "student",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="course_records",
                        to="user_app.user",
                        verbose_name="学生",
                    ),
                ),
            ],
            options={
                "verbose_name": "课程学生关系",
                "verbose_name_plural": "课程学生关系",
                "unique_together": {("course", "student")},
            },
        ),
    ]
