# Generated by Django 6.0.3 on 2026-04-17 05:49

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("user_app", "0001_initial"),
    ]

    operations = [
        migrations.CreateModel(
            name="Classroom",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("name", models.CharField(max_length=100, verbose_name="课堂名称")),
                (
                    "is_active",
                    models.BooleanField(default=True, verbose_name="是否进行中"),
                ),
                (
                    "create_time",
                    models.DateTimeField(auto_now_add=True, verbose_name="创建时间"),
                ),
                (
                    "end_time",
                    models.DateTimeField(
                        blank=True, null=True, verbose_name="结束时间"
                    ),
                ),
                (
                    "course",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="classrooms",
                        to="user_app.course",
                        verbose_name="所属课程",
                    ),
                ),
            ],
            options={
                "verbose_name": "课堂",
                "verbose_name_plural": "课堂",
            },
        ),
        migrations.AddField(
            model_name="task",
            name="classroom",
            field=models.ForeignKey(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.CASCADE,
                related_name="tasks",
                to="user_app.classroom",
                verbose_name="所属课堂",
            ),
        ),
    ]
