# Generated by Django 6.0.3 on 2026-04-26 23:51

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("user_app", "0002_classroom_task_classroom"),
    ]

    operations = [
        migrations.CreateModel(
            name="TaskScore",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("score", models.IntegerField(default=0, verbose_name="得分")),
                (
                    "create_time",
                    models.DateTimeField(auto_now_add=True, verbose_name="计算时间"),
                ),
                (
                    "student",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        to="user_app.user",
                        verbose_name="学生",
                    ),
                ),
                (
                    "task",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="scores",
                        to="user_app.task",
                        verbose_name="所属任务",
                    ),
                ),
            ],
            options={
                "verbose_name": "任务得分",
                "verbose_name_plural": "任务得分",
                "unique_together": {("task", "student")},
            },
        ),
    ]
